name: sync_client
description: A library to sync based on sqlite_wrapper
version: 1.4.4
homepage: https://github.com/stefalda/sync_client
issue_tracker: https://github.com/stefalda/sync_client/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite_wrapper: ^0.5.3
  #  path: ./../../open-source/sqlite_wrapper
  uuid: ^4.5.2
  crypto: ^3.0.7
  encrypt: ^5.0.3
  dio: ^5.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  test: ^1.28.0
