name: sync_client
description: A library to sync based on sqlite_wrapper
version: 1.0.4
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite_wrapper: ^0.1.1
  #  path: ./../../../open-source/sqlite_wrapper
  path: ^1.8.3 # Required to compute path
  #sqlite3_flutter_libs: ^0.5.7 # Required by Android
  uuid: ^4.1.0
  crypt: ^4.3.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  dio: ^5.3.3

dev_dependencies:
  flutter_lints: ^2.0.3
  lints: ^2.1.1
  test: ^1.24.7
