name: sync_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite_wrapper: ^0.1.0
  #  path: ./../../../open-source/sqlite_wrapper
  path: # Required to compute path
  #sqlite3_flutter_libs: ^0.5.7 # Required by Android
  uuid:
  http:
  # device_info_plus: ^3.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
